#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Hold the data model to the tree, and its two renderings to the data model.

THE CONTRACT

    Every config family the tree has appears in the data model EXACTLY ONCE.
    The family list is the one `scripts/check-reachability.py` derives from the
    tree, so there is one definition of "family" and not two. A family CORE
    ships is described in `docs/data-model.yaml`. A family only this instance
    has is described in `work/data-model.yaml`, which sits under `work/` and is
    therefore USER by folder: it never promotes, and a fork that adds a family
    can say what it is without touching a CORE file.

    A row names a family that exists. A row for a folder that was renamed or
    removed is drift in the other direction, and it is reported the same way.

    The table in `docs/data-model.md` and the ring in `docs/index.html` are
    GENERATED from the yaml, between marker comments. A hand edit to either is
    drift: the two pictures of one model are exactly the thing that falls apart
    when they are maintained separately.

Usage:
    python3 scripts/data-model.py            check, exit 1 on any finding
    python3 scripts/data-model.py --write    regenerate the table and the ring
    python3 scripts/data-model.py --mutate   prove every check can fail
"""

from __future__ import annotations

import argparse
import copy
import html
import importlib.util
import math
import shutil
import sys
import tempfile
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
CORE_MODEL = "docs/data-model.yaml"
INSTANCE_MODEL = "work/data-model.yaml"
DOC = "docs/data-model.md"
PAGE = "docs/index.html"

TABLE_START = "<!-- data-model:table:start (generated by scripts/data-model.py from docs/data-model.yaml; edit the yaml, then run it with --write) -->"
TABLE_END = "<!-- data-model:table:end -->"
RING_START = "<!-- data-model:ring:start (generated by scripts/data-model.py from docs/data-model.yaml; edit the yaml, then run it with --write) -->"
RING_END = "<!-- data-model:ring:end -->"

REQUIRED = ("path", "object", "island", "lives", "references", "writer", "read")
READS = ("start", "named")


# ------------------------------------------------------------------ loading --


def _reachability():
    spec = importlib.util.spec_from_file_location(
        "check_reachability", REPO_ROOT / "scripts" / "check-reachability.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def tree_families(root: Path) -> list[str]:
    """The families the tree has, derived the way check-reachability derives them."""
    return _reachability().discover_families(root)


def load_model(root: Path) -> dict:
    """The CORE model, with the instance's own rows appended when it has any."""
    model = yaml.safe_load((root / CORE_MODEL).read_text(encoding="utf-8")) or {}
    rows = [dict(r, origin=CORE_MODEL) for r in model.get("families") or []]
    extra = root / INSTANCE_MODEL
    if extra.is_file():
        local = yaml.safe_load(extra.read_text(encoding="utf-8")) or {}
        rows += [dict(r, origin=INSTANCE_MODEL) for r in local.get("families") or []]
    model["families"] = rows
    return model


def _norm(path: str) -> str:
    return str(path).strip().rstrip("/") + "/"


# ------------------------------------------------------------------ checks --


def check_rows(model: dict, families: list[str]) -> list[str]:
    problems: list[str] = []
    stores = set((model.get("stores") or {}).keys())
    seen: dict[str, str] = {}
    for row in model["families"]:
        where = row.get("origin", CORE_MODEL)
        missing = [k for k in REQUIRED if row.get(k) in (None, "")]
        if missing:
            problems.append(f"{where}: {row.get('path', '?')} lacks {', '.join(missing)}")
            continue
        path = _norm(row["path"])
        if path in seen:
            problems.append(f"{path} is described twice ({seen[path]} and {where}); once is the contract")
        seen[path] = where
        if row["read"] not in READS:
            problems.append(f"{path}: read is {row['read']!r}, one of {', '.join(READS)} is expected")
        for store in _as_list(row["lives"]):
            if store not in stores:
                problems.append(f"{path}: lives in {store!r}, which the model's stores do not define")
    for fam in families:
        if _norm(fam) not in seen:
            problems.append(
                f"{fam} is a family in the tree and has no row: describe it in {CORE_MODEL}, "
                f"or in {INSTANCE_MODEL} if only this instance has it")
    wanted = {_norm(f) for f in families}
    for path, where in seen.items():
        if path not in wanted:
            problems.append(f"{where}: {path} has a row, and the tree has no such family")
    return problems


def check_rendered(root: Path, model: dict) -> list[str]:
    problems: list[str] = []
    for rel, start, end, render in ((DOC, TABLE_START, TABLE_END, render_table),
                                    (PAGE, RING_START, RING_END, render_ring)):
        text = (root / rel).read_text(encoding="utf-8")
        current = _between(text, start, end)
        if current is None:
            problems.append(f"{rel}: the generated block is missing (markers {start[:32]}...)")
        elif current != render(model):
            problems.append(f"{rel}: the generated block differs from {CORE_MODEL}; run --write")
    return problems


def is_core_checkout(root: Path) -> bool:
    """No bridge-config.yaml, no user tier: the test the scope-router suite uses too."""
    return not (root / "bridge-config.yaml").exists()


def check_instance_file(root: Path) -> list[str]:
    """In the CORE repo there is no instance, so there is no instance file.

    Without this, a CORE family described only in work/data-model.yaml would
    pass the once-each check and still be missing from both renderings, which
    leave instance rows out on purpose. The scope-router suite exempts work/,
    so nothing else would notice.
    """
    if is_core_checkout(root) and (root / INSTANCE_MODEL).is_file():
        return [f"{INSTANCE_MODEL} exists in a checkout without bridge-config.yaml: in the "
                f"CORE repo every family is described in {CORE_MODEL}, where the tables "
                f"and the ring can see it"]
    return []


def check(root: Path) -> list[str]:
    model = load_model(root)
    return (check_instance_file(root) + check_rows(model, tree_families(root))
            + check_rendered(root, model))


# ------------------------------------------------------------- rendering --


def _as_list(value) -> list:
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def _cell(value) -> str:
    items = [str(v) for v in _as_list(value)]
    return "<br>".join(items).replace("|", "\\|") if items else "none"


def _refs(value) -> str:
    """`field` → target, with the field in code so `*_ref` never reads as emphasis."""
    out = []
    for ref in _as_list(value):
        field, _, target = str(ref).partition(" → ")
        out.append(f"`{field}` → {target}" if target else f"`{field}`")
    return "<br>".join(out).replace("|", "\\|") if out else "none"


def render_table(model: dict) -> str:
    """The four tables of docs/data-model.md, in reading order."""
    stores = model.get("stores") or {}
    reads = model.get("reads") or {}
    short = lambda keys: "<br>".join(stores.get(k, {}).get("short", k) for k in _as_list(keys))
    out = ["#### Read before the first answer", "",
           "| Item | What it is |", "|---|---|"]
    for item in model.get("always_on") or []:
        out.append(f"| {_cell(item['label'])} | {_cell(item['what'])} |")
    out += ["", "#### The config families", "",
            "| Family | One entry is | Island | Lives in | References | Written by | Read |",
            "|---|---|---|---|---|---|---|"]
    for row in model["families"]:
        if row.get("origin") != CORE_MODEL:
            continue                       # an instance's rows never reach a CORE file
        read = reads.get(row["read"], {}).get("short", row["read"])
        out.append(f"| `{_norm(row['path'])}` | {_cell(row['object'])} | {_cell(row['island'])} | "
                   f"{short(row['lives'])} | {_refs(row['references'])} | {_cell(row['writer'])} | {read} |")
    out += ["", "#### Beside the families", "",
            "| File | What it is | Island | Lives in |", "|---|---|---|---|"]
    for row in model.get("beside") or []:
        out.append(f"| `{row['path']}` | {_cell(row['what'])} | {_cell(row['island'])} | {short(row['lives'])} |")
    out += ["", "#### The stores", "", "| Lives in | Meaning |", "|---|---|"]
    for key, value in stores.items():
        out.append(f"| {_cell(value.get('short', key))} | {_cell(value.get('what', ''))} |")
    return "\n".join(out)


def _group(path: str) -> str:
    head = path.split("/", 1)[0]
    if head in ("identity", "infra", "workflow"):
        return head
    return "work" if head == "work" else "behaviour"


GROUP_ORDER = ("identity", "infra", "workflow", "behaviour", "work")


def _label(path: str) -> str:
    """The short name the ring prints: the last segment, or the whole of a dot path."""
    bare = _norm(path).rstrip("/")
    return bare if bare.startswith(".") else bare.split("/")[-1]


def _esc(text: str) -> str:
    return html.escape(str(text), quote=True)


def _both(value: dict) -> str:
    return (f'<tspan data-lang="en">{_esc(value["en"])}</tspan>'
            f'<tspan data-lang="de">{_esc(value["de"])}</tspan>')


def render_ring(model: dict) -> str:
    """One inline SVG in the page's own diagram classes, so it follows the theme."""
    ring = model["ring"]
    rows = [r for r in model["families"] if r.get("origin") == CORE_MODEL]
    rows.sort(key=lambda r: (GROUP_ORDER.index(_group(r["path"])), r["path"]))
    cx = cy = 400
    r_centre, r_band, r_named, r_walked, r_outside = 46, 182, 204, 330, 372
    rx_first, ry_first = 132, 104           # an ellipse: the labels are wider than tall
    r_group = (r_walked + r_outside) / 2    # group names sit between the two outer rings
    gap = math.radians(7)
    groups = [g for g in GROUP_ORDER if any(_group(r["path"]) == g for r in rows)]
    step = (2 * math.pi - gap * len(groups)) / len(rows)

    out = ['<svg viewBox="0 0 800 856" preserveAspectRatio="xMidYMid meet">']
    out.append(f'  <circle class="dg-bound" cx="{cx}" cy="{cy}" r="{r_outside}"/>')
    out.append(f'  <circle class="dg-track" cx="{cx}" cy="{cy}" r="{r_walked}"/>')
    out.append(f'  <circle class="dg-box" cx="{cx}" cy="{cy}" r="{r_band}"/>')
    out.append(f'  <circle class="dg-merge" cx="{cx}" cy="{cy}" r="{r_centre}"/>')
    out.append(f'  <text class="dg-lbl" x="{cx}" y="{cy + 5}" text-anchor="middle">{_both(ring["centre"])}</text>')

    # ring 1: what every session reads before its first answer
    items = model["always_on"]
    for i, item in enumerate(items):
        a = -math.pi / 2 + 2 * math.pi * (i + 0.5) / len(items)
        x, y = cx + math.cos(a) * rx_first, cy + math.sin(a) * ry_first
        out.append(f'  <text class="dg-mono" x="{x:.1f}" y="{y + 4:.1f}" text-anchor="middle" '
                   f'fill="var(--accent-text)">{_esc(item["label"])}</text>')

    # ring 2: the families, one dot each, filled where something is read at start
    a = -math.pi / 2 + gap / 2
    for g in groups:
        members = [r for r in rows if _group(r["path"]) == g]
        a0 = a
        for row in members:
            mid = a + step / 2
            dx, dy = math.cos(mid), math.sin(mid)
            fill = "var(--accent)" if row["read"] == "start" else "var(--surface)"
            out.append(f'  <circle cx="{cx + dx * r_named:.1f}" cy="{cy + dy * r_named:.1f}" r="5" '
                       f'fill="{fill}" stroke="var(--accent)" stroke-width="1.4"/>')
            lx, ly = cx + dx * (r_named + 12), cy + dy * (r_named + 12)
            left = dx < -1e-9
            rot = math.degrees(mid) + (180 if left else 0)
            out.append(f'  <text class="dg-sub" x="{lx:.1f}" y="{ly:.1f}" '
                       f'text-anchor="{"end" if left else "start"}" dominant-baseline="middle" '
                       f'transform="rotate({rot:.1f} {lx:.1f} {ly:.1f})">{_esc(_label(row["path"]))}</text>')
            a += step
        gm = (a0 + a) / 2
        gx, gy = cx + math.cos(gm) * r_group, cy + math.sin(gm) * r_group
        out.append(f'  <text class="dg-cap" x="{gx:.1f}" y="{gy + 4:.1f}" text-anchor="middle" '
                   f'stroke="var(--surface)" stroke-width="5" paint-order="stroke">{_esc(g)}/</text>')
        a += gap

    # the legend, under the rings
    y0 = cy + r_outside + 34
    out.append(f'  <circle cx="90" cy="{y0}" r="5" fill="var(--accent)" stroke="var(--accent)" stroke-width="1.4"/>')
    out.append(f'  <text class="dg-cap" x="104" y="{y0 + 4}">{_both(ring["legend_start"])}</text>')
    out.append(f'  <circle cx="90" cy="{y0 + 24}" r="5" fill="var(--surface)" stroke="var(--accent)" stroke-width="1.4"/>')
    out.append(f'  <text class="dg-cap" x="104" y="{y0 + 28}">{_both(ring["legend_named"])}</text>')
    out.append(f'  <circle class="dg-track" cx="430" cy="{y0}" r="7"/>')
    out.append(f'  <text class="dg-cap" x="446" y="{y0 + 4}">{_both(ring["walked"])}</text>')
    out.append(f'  <circle class="dg-bound" cx="430" cy="{y0 + 24}" r="7"/>')
    out.append(f'  <text class="dg-cap" x="446" y="{y0 + 28}">{_both(ring["outside"])}</text>')
    out.append("</svg>")

    doc = "https://github.com/bks-lab/open-bridge/blob/main/docs/data-model.md"
    return "\n".join([
        f'<div class="diagram-frame reveal" style="max-width:46rem" role="img" aria-label="{_esc(ring["aria"])}">',
        "\n".join(out),
        "</div>",
        f'<p class="cu-foot">{_both_link(ring["foot"], doc)}</p>',
    ])


def _both_link(value: dict, href: str) -> str:
    link = f'<a href="{href}">docs/data-model.md</a>'
    return (f'<span data-lang="en">{_esc(value["en"])} {link}</span>'
            f'<span data-lang="de">{_esc(value["de"])} {link}</span>')


# ------------------------------------------------------------ write-back --


def _between(text: str, start: str, end: str) -> str | None:
    if start not in text or end not in text:
        return None
    body = text.split(start, 1)[1].split(end, 1)[0]
    return body.strip("\n")


def _replace(text: str, start: str, end: str, body: str) -> str:
    head, rest = text.split(start, 1)
    _, tail = rest.split(end, 1)
    return f"{head}{start}\n{body}\n{end}{tail}"


def write(root: Path) -> list[str]:
    model = load_model(root)
    changed = []
    for rel, start, end, render in ((DOC, TABLE_START, TABLE_END, render_table),
                                    (PAGE, RING_START, RING_END, render_ring)):
        path = root / rel
        text = path.read_text(encoding="utf-8")
        if _between(text, start, end) is None:
            raise SystemExit(f"{rel}: place the two marker comments first, then run --write")
        new = _replace(text, start, end, render(model))
        if new != text:
            path.write_text(new, encoding="utf-8")
            changed.append(rel)
    return changed


# ---------------------------------------------------------------- mutate --


def mutate(root: Path) -> list[str]:
    """Soften the input one way at a time and demand a finding each time."""
    families = tree_families(root)
    base = load_model(root)
    survivors = []

    def needle(name, model, fams=families):
        if not check_rows(model, fams):
            survivors.append(name)

    m = copy.deepcopy(base); m["families"] = m["families"][1:]
    needle("a family loses its row", m)
    m = copy.deepcopy(base); m["families"].append(dict(m["families"][0]))
    needle("a family gets a second row", m)
    m = copy.deepcopy(base); m["families"].append(dict(m["families"][0], path="identity/gone/"))
    needle("a row names a family the tree lacks", m)
    m = copy.deepcopy(base); m["families"][0] = dict(m["families"][0], read="sometimes")
    needle("a row carries an unknown read value", m)
    m = copy.deepcopy(base); m["families"][0] = dict(m["families"][0], lives="nowhere")
    needle("a row lives in an undefined store", m)
    m = copy.deepcopy(base); m["families"][0] = {k: v for k, v in m["families"][0].items() if k != "writer"}
    needle("a row drops a required field", m)
    needle("the tree grows a family nobody described", base, families + ["infra/newcomers/"])

    # The generated blocks, in a scratch copy: a hand edit inside either one
    # must read as drift, and so must a block whose markers were deleted.
    edits = (
        ("a hand edit to the table", DOC, "| Family | One entry is |", "| Folder | One entry is |"),
        ("a hand edit to the ring", PAGE, RING_END, '<p class="cu-foot">edited</p>\n' + RING_END),
        ("the table markers are gone", DOC, TABLE_END, ""),
    )
    for name, rel, old, new in edits:
        with tempfile.TemporaryDirectory() as tmp:
            scratch = Path(tmp)
            for keep in (DOC, PAGE):
                (scratch / keep).parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(root / keep, scratch / keep)
            target = scratch / rel
            text = target.read_text(encoding="utf-8")
            if old not in text:
                survivors.append(f"{name} (its anchor is gone, so it softened nothing)")
                continue
            target.write_text(text.replace(old, new, 1), encoding="utf-8")
            if not check_rendered(scratch, base):
                survivors.append(name)
    return survivors


# ------------------------------------------------------------------ main --


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--write", action="store_true", help="regenerate the table and the ring")
    parser.add_argument("--mutate", action="store_true", help="prove every check can fail")
    parser.add_argument("--root", default=str(REPO_ROOT), help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    root = Path(args.root)

    if args.mutate:
        survivors = mutate(root)
        if survivors:
            print("data-model --mutate: these softenings went unnoticed:", file=sys.stderr)
            for s in survivors:
                print(f"  - {s}", file=sys.stderr)
            return 1
        print("data-model --mutate: every needle produced a finding")
        return 0

    if args.write:
        changed = write(root)
        print("data-model: rewrote " + (", ".join(changed) if changed else "nothing, all in sync"))
        return 0

    problems = check(root)
    if problems:
        print("data-model: the model and the tree disagree:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1
    rows = load_model(root)["families"]
    local = sorted(_norm(r["path"]) for r in rows if r.get("origin") == INSTANCE_MODEL)
    note = (f" ({len(local)} described in {INSTANCE_MODEL} and left out of both renderings: "
            f"{', '.join(local)})") if local else ""
    print(f"data-model: {len(rows)} families, each described once{note}; "
          f"table and ring match {CORE_MODEL}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
